### ISSUE TITLE
mysqli_real_connect(): (HY000/2002): No such file or directory

### ISSUE THREAD

**Issue by MichalZahir** [cloudfoundry-samples/cf-ex-phpmyadmin#13]
After the php admin is up and running in the Foundry Cloud. 
It seems that I cannot login to the PHP admin due to mysqli_real_connect(): (HY000/2002): No such file or directory.

**Comment by dmikusa-pivotal** [comment]
Please review this section of code:

https://github.com/cloudfoundry-samples/cf-ex-phpmyadmin/blob/master/htdocs/config.inc.php#L27-L48

It makes an attempt to read your MySQL configuration from bound MySQL services. It covers common cases like using 'cleardb' or 'p-mysql', services tagged with 'mysql' and services where you put 'mysql' in the name.

You probably need to adjust the code so that it finds your bound MySQL config. If you include a sanitized copy of `cf env` for your app, I can give you some pointers.

**Comment by vlvanchin** [comment]
> If you have an existing db service with some arbitary name, please re-name the service such that it contains the *mysql* word as the *config.ini* file checks for *mysql* word for loading the service. This will avoid #8 issue
